### ISSUE TITLE
Application Loading Error

### ISSUE THREAD

**Issue by witchdoctor928** [JustSomeGuy1234/WrestlingEmpireCustomMusic#7]
When attempting to load the application, the command screen pops up and displays the following error:
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
	at BytesToPatch.Program.Patch()
	at BytesToPatch.Program.Main(String[] args)
Then the window closes. This also occurs if you extract the files before running the application.
![custom music error](https://user-images.githubusercontent.com/101912066/159102948-edb241d2-cbe0-49c6-ba24-1488f3e89a6f.png)

**Comment by JustSomeGuy1234** [comment]
It's a very vague error message but I've found a potential cause. 
The application reads a string value named SteamPath within the registry key:
HKEY_CURRENT_USER\SOFTWARE\Valve\Steam\
It does this to find the game's installation folder. However, If this key is not found it produces an identical error message to yours. 

I imagine this would only happen if you don't have Steam installed, and are using a pirated version of the game (i don't care). 
Whether or not you're using a pirated version [you should check whether the key exists using the Registry Editor. If it doesn't exist, manually create the above key in the registry](https://youtu.be/Rs2-ikaMldM?t=37). This should trigger the manual installation dialogue for the application, letting you install the mod manually.
I will probably release a fix for this in the next update.

If the key exists though, this would not be the cause of the issue and I'm not sure how else I would be able to tell what it is due to the unfortunately mysterious error message.

**Comment by witchdoctor928** [comment]
Thank you that fixed it, thank you for the hard work you did on this mod.
